### ISSUE TITLE
How to write a custom allocator for IGpuAllocator

### ISSUE THREAD

**Issue by VCBE123** [NVIDIA/tensorrt-laboratory#35]
![image](https://user-images.githubusercontent.com/30370620/80362287-f4286400-88b4-11ea-8a5b-3e15614190fb.png)

How to write a custom allocator for the IGpuAllocator, So that I can release the resource to OS.

**Comment by ryanolson** [comment]
TensorRT provides an abstract allocator interface as you point to above.  You can find examples of how I used that in this project below:

https://github.com/NVIDIA/tensorrt-laboratory/blob/master/tensorrt-laboratory/tensorrt/include/tensorrt/laboratory/allocator.h

However, it is not the job of the custom allocator to release resources to the OS, but rather, the custom allocator is used to tell TensorRT to use memory from this new source that is not cudaMalloc.

In our application, you might have your custom allocator, like Tensorflow does.  The size of this memory pool might consume the majority of the GPU memory on you node.  That would cause TensorRT to fall to acquire the memory resources it needs to store the weights, buffers and intermediates it requires for computing inference.

That's why you'd use the IGpuAllocator.  

To be clear, you can not use the IGpuAllocator interface to release resources held by TensorRT.  To do that, simply deallocate those resources with `destroy` methods.

TensorRT does allow for very fine grain control over memory management.   Let's look at the lifecycle of an inference model and annotate the memory requirements.

Assuming you have successful built and serialized a TensorRT model to disk.  You have a file called `model.engine` in your filesystem.

To consume it in TensorRT, you need to read the `model.engine` file into memory, then deserialize using an IRuntime object.  As mentioned above, you can override the default allocator of the IRuntime with an IGpuAllocator. 

You use the `IRuntime::deserializeCudaEngine` call consume the blob of bytes you read from disk.  In this process TensorRT will allocate storage for the weights and biases of the model being loaded to the current cudaDevice.  These allocations are owned by the ICudaEngine object created by calling deserializeCudaEngine.  To free them, destory the ICudaEngine.   You can now deallocate the host memory used to load the .engine file to memory since the data has been consumed and moved to the device.

The total storage for your model is simply the total number of bytes required to hold the weights, biases and possibly some calibration data if using INT8.

When you want to execute inference on the model, you need to require an IExecutionContext from the ICudaEngine.  This can be one in one of two ways:

1. ICudaEngine::createExecutionContext
2. ICudaEngine::createExecutionContextWithoutDeviceMemory

All IExecutionContexts own opaque handles to cublas and cudnn.  This have a small but measurable memory footprint.  Option #1 above has a third component which hold the memory required for the activation scratch space of the model.  This is memory once allocated is ONLY available to the IExecutionContext and not to the rest of the program.  The alternative option requires you to provide some chuck of memory of size `getDeviceMemorySize` to the IExecutionContext before calling `enqueue/execute` or the corresponding v2 alternatives.

The second method is preferred if you wish to limit the memory footprint of non active models without incurring the cost of creating/estroying the IExecutionContext on demand.  You still hold some memory for the handles, but free up the activation space memory which can be very significatn.
